socrata-platform/soda-fountain

- bin/run_migrations.sh
Addressed feedback from Marc S and John K in https://github.com/socrata/soda-fountain/pull/67.
> Onramp fixes to run_migrations.sh

- project/BuildSettings.scala
- project/Dependencies.scala
- project/SodaFountainExternal.scala
- project/SodaFountainJetty.scala
- project/SodaFountainLib.scala
- project/SodaFountainWar.scala
- project/plugins.sbt
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaRouter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ExportDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/ComputeUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/Decoder.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/computation/GeoregionMatchOnPointHandlerTest.scala
Updated the code to include new socrata-sbt-plugin.
> Socrata-SBT-plugin 

- .gitignore
- docker/Dockerfile
- docker/README.md
- docker/ship.d/run
- docker/soda-fountain.conf.j2
- project/Dependencies.scala
- soda-fountain-lib/src/main/resources/reference.conf
Note that soda-fountain doesn't currently support liveness checks on
the server side, so none of that is configured for docker.
> Add docker support for soda-fountain.

- project/plugins.sbt
Good news and Bad news
+@chitang @AEscobarCruz and everyone wants this to build
+This change will successfully build and publish
-@velvia likes Codacy
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soda-fountain/79)
> remove codacy coverage plugin

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnSpecUtils.scala
Stan found a bug where we cannot create column with computation strategy.
> BUG: Cannot create column with computation strategy.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
+ must use URI to form http request
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soda-fountain/88)
> http tweaks

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/GeoJsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepPerfBench.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepTest.scala
- faster .geojson export
- faster regular .json export with geometry columns
- faster geometry ingestion
More to come later.
> Faster geometry serialization

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
report 404 if something isn't found.
> es mimetype is not json

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaRouter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
+ plumbing to route suggest sample requests from core to spandex
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soda-fountain/94)
> add suggest sample endpoint

- project/SodaFountainLib.scala
- soda-fountain-lib/src/main/resources/reference.conf
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/CuratedHttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SpandexTestSuite.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soda-fountain/98)
> Spandex Timeouts

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
If a source column in computation_strategy becomes invalid for whatever reason, Soda Fountain currently blows up trying to read its (non-existent) column definition (see stack trace below). Fixing that.
```
2015-04-07 16:28:45,998 ERROR [6078 / DELETE /dataset/_wfqv-uxqr/%3A%40computed_region_mv22_r2ri] (2a282bfbe72b3be687a292596efcedec) [] Error Internal exception: 0810c56d-cf9d-45c3-8a72-321f67acbe4d
org.postgresql.util.PSQLException: ResultSet not positioned properly, perhaps you need to call next.
at org.postgresql.jdbc2.AbstractJdbc2ResultSet.checkResultSet(AbstractJdbc2ResultSet.java:2675)
at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getString(AbstractJdbc2ResultSet.java:1852)
at org.postgresql.jdbc2.AbstractJdbc2ResultSet.getString(AbstractJdbc2ResultSet.java:2385)
at …
```
> Check the result set in fetchMinimalColumn before trying to read things out of it

- project/SodaFountainLib.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SpandexTestSuite.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
finish test suite for soda-fountain suggest resource
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/socrata/soda-fountain/99)
> Suggest Tests

- soda-fountain-external/src/main/scala/com/socrata/soda/external/SodaFountainClient.scala
This will be helpful for very large upserts and in particular help geospace not have to keep too much in memory during uspert time.
> New method added to stream json upserts to Soda. 

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ExportDAOImpl.scala
Really quick thing to help debug CORE-4935 etc.
> Get more visibility into CJSON decoding error messages

- soda-fountain-lib/src/main/resources/reference.conf
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/geospace/GeospaceClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/HealthZ.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/HealthZTest.scala
> Improve /healthz endpoint to provide more useful info when it fails

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepTest.scala
Also enables us to ingest what is exported from NBE via CSV.   :)
> Parse WKT values on ingest (enables CSV geom ingest)

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/GeoJsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/SoQLPackExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/CsvColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepTest.scala
* added multipoint polygon and line types
* added soql tests
* TODO: update the dependencies file and remove the snapshot reference
> Refs CORE-5412

- bin/start_soda_fountain.sh
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
- don't lookup copy number from truth
+ pass `stage=published` to spandex-http for lookup in secondary instance
> ask spandex to get the latest published copy

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnSpecUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Version.scala
Lets try to make the logs a bit more readable by not doing that.
> Logging TODOs is amusing, but not a very effective way of fixing things, as history has shown.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
Basically we were trying to pull out the same header from an HttpRequest twice. Changed the code to pull it out once and subsequently pass it between methods.
> Don't generate multiple request IDs in a single request.

- soda-fountain-lib-macros/src/main/java/com/socrata/soda/server/macros/Tag.java
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorError.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/errors/error.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/id/AbstractId.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
error handling is complicated and do not work well.  This is not a complete solution to the problem.  I hope this is an improvement and should have better coverage.
> passing dc errors

- soda-fountain-lib/src/main/resources/reference.conf
* increase the size of the max datum so that we can
deal with shapes that have more than ~5000 vertices
> Refs CORE-6922

- project/Dependencies.scala
- project/SodaFountainLib.scala
- soda-fountain-jetty/src/main/scala/com/socrata/soda/server/SodaFountainJetty.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/CuratedHttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/CuratedHttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/regioncoder/RegionCoderClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/GeoregionMatchHandler.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/CsvColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/SoQLLiteralColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/StringColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/computation/GeoregionMatchOnPointHandlerTest.scala
It's pretty trivial since there's nothing soda-fountain can do with these except pass them through.  They aren't even eligible to be primary keys (which is why it's commented out in `StringColumnRep`).
> Add SoQLBlob support

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/errors/error.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/NameAndSchemaStore.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
Required for geoserver migration UID swap
> Allow patching of dataset resource name

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
added response parameter to withColumnSpec in order to respond appropriately with error responses instead of an empty 200.
> Expose unsupported column type creation errors. 

- docker/soda-fountain.conf.j2
> Refs EN-1737

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
The final rollup soql saved in pg should not be wrapped by LIST(soql).
> BUG: EN-1783 - rollup soql should not be chained.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ExportDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ExportDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
Should help in performing region coding much more efficiently and with less memory constraints than loading full rows to memory.
> additional logic added to export only certain columns

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
We assumed that all system columns clumps together which does not hold for computed columns.  Now that DC export does support specifying columns, SF will use that to exclude system columns.
> Exporting with computed column fails when exclude_system_fields = true

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/CJsonExporter.scala
Got lost in the resourcescopeification in commit 8b6e98c264928e
> Make sure to put a charset on cjson responses

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- version.sbt
There isn't an immediate need.  Just to keep project up-to-date.
> Use latest soql-reference for type check simplification.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
So responses don't get cut off in the middle.
> Use the right resource scope when querying

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
Previously this failed with upsert-error-malformed-report-item-id
because these end up as JNumbers, not JStrings. Dates appear to be taken
care of as strings already.
> EN-3709: allow single-row upsert with custom row ids which are integers

- docker/Dockerfile
So far so good building and running in staging. Will merge when it's sat there peacefully for a bit.
> EN-5914: Use java8 base image for soda-fountain

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/ColumnMutation.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnSpecUtils.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/ColumnMutationTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnSpecUtilsTest.scala
Move computation parameter transformation such that
the parameters are transformed in both metasoda and truth.
> EN-4817: Move computation parameter transformation

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
Specifically retry on HTTP connection failure.
> Add some retry logic around executing a query

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorErrors.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/responses/responses.scala
This error happens when you ask for creating working copy which already exists.
The return code is 409.  There was also typo/inconsistent use of stage and state which caused decoding problem.
> Relay invalid life cycle stage error.

- docker/soda-fountain.conf.j2
> Add new `computation-strategy-secondary-id` to docker

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/Exporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/TableExporter.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/ExporterTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/GeoJsonExporterTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/TableExporterTest.scala
> EN-8949: handle .tsv files

- project/Dependencies.scala
These functions provide support for the apps team.
All is needed here is bump soql-lib.  This only matters for rollups.
> EN-14870 Add date_extract_xxx(floating_timestamp) functions. (#100)

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/GeoregionMatchHandler.scala
looks like scalaj.http doesn't wrap IO exceptions it can receive in
its own exception type.
> Retry region coding on IO exceptions as well as HTTP exceptions

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20171006-increase-column-name-size.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
** Manual Migration Preferred **
> EN-19227 Do not restrict columns.column_name size

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/CsvColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
> EN-19703 Add SoQLDocument type

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
Updated soda-fountain to properly parse the response from data-coordinator for collocate operations.
> Collocation Response Updated

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/LocationFuser.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
> EN-29006 fuse column - location in cjson export for dsmapi

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
> EN-30766 Return truth data version that data coordinator gives us

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
In particular, on publication lifecycle operations
> EN-30766 Return more truth data version from data coordinato

- configs/sample.conf
- docker/soda-fountain.conf.j2
- project/Build.scala
- project/Dependencies.scala
- project/SodaFountainMessageLib.scala
- soda-fountain-lib/src/main/resources/reference.conf
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/CJsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/Exporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/GeoJsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/JsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/SoQLPackExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/TableExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/SnapshotDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/GeoJsonExporterTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/SoQLPackExporterTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/TableExporterTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/metrics/QueryMetricTest.scala
- soda-fountain-message-lib/src/main/scala/com/socrata/soda/message/ActiveMQServiceRawProducer.scala
- soda-fountain-message-lib/src/main/scala/com/socrata/soda/message/Message.scala
- soda-fountain-message-lib/src/main/scala/com/socrata/soda/message/MessageProducer.scala
Not yet turned on.  Config will be done in docker files.
> EN-36489 Fire rows_loaded_api metrics messages

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/QueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
> EN-41615: Plumb the resource-name down to QC too

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/CsvColumnRep.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/CsvColumnRepTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepTest.scala
0.0000005302 should be written as is (not 5.302E-7)
> EN-46154: Do not produce scientific notation on SoQLNumber

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
This will retry on connect failure for side-effecting or streaming
operations, or on _any_ IO failure for non-side-effecting, non-streaming
ones.
> Add retries while talking to data-coordinator

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/NameAndSchemaStore.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/PostgresStoreTest.scala
Via X-Socrata-Deleted-At header
> EN-51148: Expedited dataset delete

- version.sbt
https://di-tylertech.slack.com/archives/C0KQLQTMZ/p1652718743552309
> bump to major version 4.0.0

- .run/soda-fountain.run.xml
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RollupHelper.scala
- adding wildcard expansion for piped rollups queries
- (maintenance) adding run configuration for IDEA
> EN-56812 Rollups using chained queries do not work

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RollupHelper.scala
Real fix is in soql-reference.
This change brings in the new version of soql-reference.
Some signatures have changes, so slight migration.
> EN-57981: Column mapping fix

- Jenkinsfile
After building docker image, it is pushed to all registries.
After building docker images:
- if the image is for staging, it is pushed only to the internal registry
- if the image is for release, it is pushed to all registries
> EN-60862: for staging push only to internal

- Jenkinsfile
This commit adds integration for the release metadata service for release builds.
See https://github.com/socrata-platform/soql-postgres-adapter/pull/646
> EN-62410: RMS integration

- Jenkinsfile
I accidentally pushed a commit to main rather than to my PR branch to test something out.  This commit reverts that commit:  https://github.com/socrata-platform/soda-fountain/commit/616dc94a3cf1b2597475ac931fc0c03c3d10171b
> Fix accidental commit to main

- docker/soda-fountain.conf.j2
> EN-68825: Make j2 template safer for resource groups

- Jenkinsfile
- README.md
This commit updates the automation for publishing the library. The Jenkins job for the main branch will check for the change and publish the library.
> EN-65991: publish library automatically

- .gitignore
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resource_groups/ResourceGroupsClientFactory.scala
Something about our hostname is not plumbing down how we expect, lets print our api host at config time.
> Resource groups debugging

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/QueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/FoundTablesRequest.scala
See the corresponding query-coordinator commit for details
> EN-77403: Finer-grained "preserve syscol" choices
