socrata-platform/soda-fountain

- README.md
- project/BuildSettings.scala
- project/plugins.sbt
Adds the codacy code coverage plugin and updates scoverage to 1.0.1.
NOTE: these are temporary steps to test out code coverage on codacy.  The long term answer is to add the codacy plugin to the autoplugins repo.
> Add codacy code coverage; update to SCoverage 1.0.1

- project/Dependencies.scala
- soda-fountain-jetty/src/main/scala/com/socrata/soda/server/SodaFountainJetty.scala
- soda-fountain-lib/src/main/resources/reference.conf
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- Use the newer version of socrata-http with bounded queues by default
- Add default config values, which can be overridden
> Don't fall over on high load

- soda-fountain-lib/src/main/resources/reference.conf
At 500, we should be able to keep /version running.  Might have to tune it some more, but better than the previous value.
> Reduce queue length to keep request latency lower

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepPerfBench.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/wiremodels/JsonColumnRepTest.scala
Speed up CJSON serialization by writing and reading geometries as base64 WKB.   For compatibility purposes, the decoder will fall back to WKT (so that we can upgrade SF before ugprading PG server).
Add more stuff to a perf benchmark.
NOT READY FOR MERGE yet.  Need to publish and release soql-reference PR first.
> Use WKB for CJSON Geometry types

- project/BuildSettings.scala
- project/Dependencies.scala
- project/SodaFountainLib.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/Exporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/SoQLPackExporter.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/SoQLPackDumper.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/export/SoQLPackExporterTest.scala
You can read about the details in SoQLPackExporter.scala, but this is a new, binary, highly efficient export protocol.  Initially only geometry, text, boolean columns are supported, which is enough for minimal tests and the tile server.
A tool to aid in debugging SoQLPack output is also included.
> New SoQLPack Binary Protocol

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/MutationScript.scala
This logs upserts every 50,000 instructions to make it easier to debug/track progress for both ingress and compute routes.
> Log upsert progress

- project/Dependencies.scala
- soda-fountain-external/src/test/scala/com/socrata/soda/external/SodaFountainClientTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
- using the Grisu Double toString serializer
- using optimizations in third-party-utils GeoJSON encoder
GeoJSON export should be roughly an order of magnitude faster.
> Speed up GeoJSON export

- docker/ship.d/run
Most of our migrations are ideally run _before_ a new version of a service is running. In some cases, not running the migrations beforehand can lead to outages. 
It's not uncommon that we forget to run migrations at the appropriate time to each environment; this change makes sure that never happens. 
The upshot of this is that if we have a migration that needs to be run *after* changes to the service, we'd need to deploy the service code change and the migration in 2 separate steps.
> Run metasoda migrations when the container starts.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/errors/error.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnDAOSpec.scala
The lack of validation for this scenario has resulted in some hairy situations in production - let's just prevent it from happening in the first place.
> Disallow source columns from being deleted without removing the dependency first

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
Subtle bug in the dataset lookup SQL query that prevents the most recent dataset copies from being returned if there have been any discarded working copy on a dataset. This prevents any subsequent working copies from being created.
> Fix dataset lookup bug

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
This log message currently spams the soda fountain log every 30 seconds - removing it.
> Remove unnecessarily noisy table dropper log messages

- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
Mock http requests need to expect get request id call.
> Fix test break due to socrata-http version bump.

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20160216-drop-recompute-from-computation-strategies.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/sql/drop_recompute_from_computation_strategies.sql
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/ColumnMutation.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumnsLike.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/GeoregionMatchOnPointHandler.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/GeoregionMatchOnStringHandler.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/TestComputationHandler.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnSpecUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDataTranslator.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/package.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/NameAndSchemaStore.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/ComputationStrategySpec.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/ComputationStrategyType.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/ColumnMutationTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/MutationScriptTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/DatasetsForTesting.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/computation/GeoregionMatchOnPointHandlerTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/computation/GeoregionMatchOnStringHandlerTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnSpecUtilsTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/PostgresStoreTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/services/ComputationStrategyExtractorTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/services/DatasetExtractorTest.scala
- Also passes on field `names
- Makes computed columns with type "geocoding"
not be named with ":@" so they are visible
- Removes unused `recompute` column
> EN-158 Passes comp strategies onto datacoordinator

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/PostgresStoreTest.scala
Maintain reference to recompute column on the write
path until the column as a default value.
Refs EN-3506
> Fix: Drop recompute column safely (part 1)

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20160308-add-recompute-default-value.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
Add default value for recompute column, so references
to it can be removed in the future.
> EN-3506: Drop recompute column safely (part 1.25)

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
Remove all references to the recompute column.
-- Must be in a seperate release from commit
f1831a6e5ec584d640c79fdab4350be4efab8996
--
> EN-3506: Drop recompute column safely (part 1.5)

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/JsonColumnRep.scala
{ "human_address": {"city": "seattle" }, "latitude": 5.5, "longitude": 6.6 } 
in addition to:
{ "human_address": "{\"city\": \"seattle\" }", "latitude": 5.5, "longitude": 6.6 } 
to match obe capability.
> Allow this location form:

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
The main urgency around this ticket is to reduce load on ActiveMQ. Given there was some ambiguity around whether we want to rip out metrics completely or send them to Graphite, this commit simply redirects all soda-fountain metrics to the `NoopMetricProvider` for now. Once Slemko is back from vacation we can discuss if we want to redirect those metrics to Graphite.
> EN-2679: Do not send soda-fountain metrics to AMQ

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaRouter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/ComputeUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Snapshots.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/SodaResource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Suggest.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/responses/SodaResponse.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/responses/responses.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/ColumnSpec.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/ComputationStrategySpec.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/DatasetSpec.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/ExtractResult.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/InputUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/wiremodels/RollupSpec.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/services/ComputationStrategyExtractorTest.scala
We keep logging things like "Error  responding with error not-modified:
Resource was not modified".  This offense my delicate sensibilities
as this isn't an error and we shouldn't say it is.  So rename the use of
"error" to be "response".
When reviewing, ensure nothing is actually changing in the HTTP
response.  All changes should be internal and only expressed in how
things are logged to avoid compatibility issues.
> EN-6972: Not all non-200 responses are errors!

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20160309-drop-recompute-from-computation-strategies.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/sql/drop_recompute_from_computation_strategies.sql
Drop recompute column only after all instances of
soda-fountain no longer reference the column.
-- Must be in a seperate release from commit
c1553f284b9fa4e6a6ee3b20a79b04722617c539
--
> EN-3506: Drop recompute column safely (part 2)

- project/Dependencies.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnSpecUtilsTest.scala
New version of library implements validation for
`georegion_match_on_point` and `georegion_match_on_string`
computation strategies.
> EN-6888: Bump version of computation strategy lib

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaException.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputationHandler.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/export/GeoJsonExporter.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/CJson.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDataTranslator.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/responses/responses.scala
requests
Then at the top level, handle these appropriately with 4xx and 5xx
responses and logging.
Also fix one spot where we were erroneously throwing
CannotDeletePrimaryKey instead of DeleteWithoutPrimaryKey.
> EN-5555: divide soda exception classes into internal errors and invalid

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumns.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumnsLike.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputingGate.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/TestComputedColumns.scala
Controlled via zookeeper; defaults to "region-coding is enabled".
> Switch to turn off region-coding in soda-fountain

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/FeedbackSecondaryManifestClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnDAOSpec.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/DatasetDAOSpec.scala
Support the ability to add datasets with computed columns to
the secondary manifest for the appropriate feedback secondary.
* Map from `computation_strategy` to (feedback) `secondary_id`
is configurable.
> EN-6887: Add region/geocoded datasets to secondary manifest

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
Changes to `/dataset-version/_4x4` endpoint:
* `truth_version` is now optional
* adds `latest` data-version
* adds `published` data-version
* adds `unpublished` data-version
* adds `groups` - a map from `group_name` to the set of
`store_id`s (only the `store_id`s that the
dataset is replicated to)
All new fields are optional.
> EN-5578:  Expand `/dataset-version/_4x4` endpoint

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Compute.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/ComputeUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/ComputeTest.scala
When computing a newly created computed column, if
computation fails, then close the export from
data-coordinator before trying to drop the column
from truth.
> EN-123901: Don't deadlock when region coding fails

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DatasetCopyInstruction.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/MutationScript.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
Pass on dataset `resource_name` in mutation script
to data-coordinator upon dataset creation. This is
so secondary-watcher can send replication complete
events with dataset external ids for waiting for
computing column statistics.
> EN-15144: Pass resource_name to data-coordinator

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumns.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumnsLike.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputingGate.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDataTranslator.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/TestComputedColumns.scala
- Refactor ComputingGate to accept a resource name and then check if it exists in a whitelist (stored in Zookeeper) before deciding whether or not to send the geo- or region-coding job to the secondary as opposed to doing it in Soda Fountain itself.
- We are doing this so that we can selectively test the correctness and stability of the new geo- and region-coding secondary on a dataset-by-dataset basis before turning it on globally per environment.
- We expect the entire ComputingGate mechanism to be removed at the same time that we disable Soda Fountain's geo- and region-coding functionality.
> EN-16161 - Add Zookeeper Whitelist for Secondary Geo- and Region-Coding

- soda-fountain-lib/src/main/resources/reference.conf
We want a general policy of 2 weeks so we will configure soda fountain to have
an extra day just so we don't run into a case where code upstream hasn't dropped it
yet but soda fountain has.
> EN-16106: Increase table drop delay to 15 days.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/SodaResource.scala
We don't pass user infomation down to sf so it just logs a silly
message.   Not ripping it out entirely because that would also require changes
in DC... we certainly could easily start passing down a user for debugging info but that
wouldn't be in the Authorization header since it isn't auth.
> Stop logging about not getting a user passed in, we know we don't do that.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/computation/ComputedColumnsLike.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/ComputeUtils.scala
Don't do extra work when computation has been
disabled for a given dataset. The uneeded upserting
of the source column done by soda-fountain is
causing geocoding secondary to get 409s while
it is trying to region code large datasets.
> EN-17534: Don't do work when computation is off

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20170712-add-datasets-deleted-at-index.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
- soda-fountain-lib/src/main/resources/reference.conf
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/config/SodaFountainConfig.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/Migration.scala
And add index on datasets(deleted_at).  Looking up datasets to delete was the 
second most expensive query hitting soda-fountain by CPU.
> EN-17537: Don't check for deleted tables to drop insanely frequently.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/ComputeUtils.scala
Call the success handler when skipping computation when computation
is not enabled for a dataset. So soda-fountain can return the correct
response when a computed column is created. Also note this means
when the /compute endpoint is used and the computing gate is off
it will say it computed 0 rows (which is true).
> EN-17534: Fix bug in 73dfa0c6ecdfd5e1930b369e5a9dcdb9c04322a8

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/HttpDatatCoordinatorClientTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/metrics/QueryMetricTest.scala
This is at least useful for development
curl -H ‘X-Socrata-Collocate: true’ ‘http://sf:6010/resource/4x4?$query=select * join @x on @x.c=c’
> A very basic backup plan to collocate dataset on soda2 query.

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnSpecUtils.scala
Work around how coreserver serializes JSON (i.e. removing fields
containing empty objects). No creating geocoding computed columns
with no sources succeeds with status 200.
> EN-7442: Allow empty sources on geocomputed column

- project/Dependencies.scala
To support changes here: https://github.com/socrata-platform/soql-reference/pull/92
> EN-19155: bump soqlReference version to 2.9.1 to support CollectionExtract fns

- .gitignore
- bin/run_migrations.sh
- bin/start_soda_fountain.sh
- configs/application.conf
- configs/sample-soda-fountain.conf
Remove references to `soda2.conf` and replace them with checked in
configs. A gitignored file `configs/local-soda-fountain.conf` can
be used to customize the configuration for local development.
> SPARTA: Stop using soda2.conf

- .gitignore
- configs/application.conf
- configs/sample.conf
Clearly comment that it was for solo (becaus I was confused).
Also, a little bit of config renaming to match spandex based
off of code reviews there.
> EN-22044: Explicit use of local.dev.socrata.net

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
Added jobID parameter to collocate endpoint for use by data-coordinator. Soda-fountain now returns full status received from data-coordinator. This makes the soda layer behave a bit more transparently for collocations.
> EN-21909: Passing JobID for Collocation

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/CollocateOperation.scala
Pass on cost limits to data-coordinator so data-coordinator
may reject collocation if the cost exceeds the passed limits.
Warning: this is a breaking change since the new fields in the
collocation request are required. Soda-fountain should be deployed
prior to data-coordinator to not cause errors.
> EN-17026: Pass data-coordinator collocation limits

- bin/run_migrations.sh
- bin/start_soda_fountain.sh
- bin/start_soda_fountain_docker.sh
- docker/ship.d/run
So that it actually uses the local development configs
in the configs directory.
Also, add full paths in the scripts in bin so
`solo start soda-fountain` can be run outside the soda-fountain
directory.
> SPARTA: Fix solo docker start script

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20190408-give-defaults-to-obsolete-datasets-columns.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/migrate.xml
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ExportDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/package.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/NameAndSchemaStore.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/DatasetsForTesting.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/PostgresStoreTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
The primary key and schema hash columns are written to but henceforth
almost ignored, so make them ignorable.  Future update once this is
out will actually drop them.
The resolveSchemaInconsistency method actually used them, but it was
incorrect to do so.  I've changed it so it operates on a particular
copy, which is what it should have been doing all along.
> The datasets table has unused columns, ignore them

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorErrors.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DatasetCopyInstruction.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/HttpDataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/MutationScript.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/ColumnDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Dataset.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/DatasetColumn.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/SodaResource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/UpsertUtils.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/responses/responses.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/MutationScriptTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/ColumnDAOSpec.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/metrics/QueryMetricTest.scala
Right now the source of this gate is a header on the request (just
like the output path, X-SODA2-Truth-Version) or, for upserts, a query
param expectedDataVersion because core uses soda-java as a
soda-fountain client when upserting and it's not obvious how to plumb
a header through soda-java without impacting the public API presented
there.
> EN-30766 allow writes to be gated on data version

- project/Dependencies.scala
this update teaches the soqlpack encoder how to handle SoQLUrl
> EN-32793: update soql-reference version to 2.11.13

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/SodaFountain.scala
The CPU overhead is fairly minimal and the network cost adds up quickly.
> Enable HTTP content compression on requests to qc / dc.

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
* receive 'brokenSecondaries' key from data-coordinator (optionally, for deploy compatibility)
* make things that were optional for much-past deploy compatibility non-optional now
> add broken secondaries to replication endpoint

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDataTranslator.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Export.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/highlevel/RowDataTranslatorTest.scala
To use plain row id, update both truth and pg secondary for the dataset in metadb as follow:
1. update dataset_map set obfuscation_key = E'\\000' where resource_name = '_four-by-four'
2. pass in $$obfuscate_id=false in both read and write (upsert) in resource/_four-by-four?$$obfuscate_id=false
> EN-37321 Support unobfuscated row id in write

- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/20140613-add-computation-strategies-table.xml
- soda-fountain-lib/src/main/resources/com/socrata/soda/server/persistence/pg/sql/computation_strategies_create.sql
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/NameAndSchemaStore.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
Currently snapshotter is looping constantly trying to snapshot datasets
that are deleted, and failing because they can't be accessed because they
are marked deleted.  To avoid this we filter out deleted datasets.
The only other uses of bulkDatasetLookup are in collation related code, and
they don't make sense for deleted datasets either and/or already won't work
if the dataset is deleted.  I'm adding it as a paramter instead of
hardcoding it to help any future users of the method think about if they
want to include deleted datasets or not.
> EN-38315: Don't try to snapshot deleted datasets.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/persistence/pg/PostgresStoreImpl.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/PostgresStoreTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/resources/SuggestTest.scala
While I'm here add a test like I should have done the first time.
> EN-38315: Fix inverted logic around excluding deleted datasets from snapshot list.

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
We currently have various datasets that don't exist on truth any more but
are still in soda fountain and it is constantly looping through trying to
delete them.
The error handling and logging here could use a much bigger overhaul, but I'm
leaving that alone for now.
> If a deleted dataset isn't known to data-coordinator, drop it.

- Jenkinsfile
For release cuts, it would exit if there were no changes and the "FORCE_BUILD" option was false.
If the "FORCE_BUILD" option was true, then it would fail in the "Publish" stage because artifactory doesn't let us publish if there are no changes.
However, we now need to rebuild and deploy even if there are no changes to the repo to pick up base layer changes for aqua compliance.
For release cuts, if there are no changes, it will rebuild from the current tag and skip the publish stage.
I removed the "FORCE_BUILD" logic since we want that to happen every time "RELEASE_CUT" is true.  I'll remove the "FORCE_BUILD" parameter from the cut job once this is merged.
> EN-54122: update jenkinsfile for releasing with no changes

- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
Previously we only catch parse error.  But there is more work after parsing that has potential to err.
> Expand error (type) handling when bad rollup is encountered

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/QueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAO.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/RowDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/Resource.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/metrics/QueryMetricTest.scala
Query coordinator needs the lens id for soql analysis. Core sends it but soda fountain was swallowing it.
> EN-54831 - pass lens id through to query coordinator

- Jenkinsfile
In the Jenkinsfile, on release cuts, the dockerized image deployed to RC.
In the Jenkinsfile, on release builds, the dockerized image is not deployed to RC.
Also: 
- new parameter RELEASE_DRY_RUN added to ease testing
- changed stage name from "Cut" to "Release Tag"
- used simpler syntax for deploying
- simplified logic for which stage to build
> EN-59948: update Jenkinsfile

- project/Dependencies.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/QueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/NewResource.scala
When told we're looking at a location column, find its subcolumns and pass this information down to query-coordinator
> EN-60548: Fake-locations on the new query path

- Jenkinsfile
- soda-fountain-jetty/build.sbt
* The filename no longer contains the version number
* The file is stored in target instead of target/scala-$version
> Simplify assembly filename

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/HttpQueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/querycoordinator/QueryCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/NewResource.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/NewRollup.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/util/DAOCache.scala
Before:
* the request sent to QC contained a map of maps which represented legacy location columns per involved dataset. Now:
* The request sent to QC contains a map of per-dataset auxiliary information.  It includes both the location column info as before as well as the current truth data version and the SF resource name.
> Generalize locationSubcolumns for data-out-of-date

- Jenkinsfile
This commit moves the release tagging after a successful docker build. In order to do this, it separates the docker build from the publishing of the images into separate Jenkinsfile steps.
> EN-65713: move release tagging

- soda-fountain-lib/src/main/scala/com/socrata/soda/clients/datacoordinator/DataCoordinatorClient.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/highlevel/DatasetDAOImpl.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/id/AbstractId.scala
- soda-fountain-lib/src/main/scala/com/socrata/soda/server/resources/NewRollup.scala
- soda-fountain-lib/src/test/scala/com/socrata/datacoordinator/client/HttpDatatCoordinatorClientTest.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/DatasetsForTesting.scala
- soda-fountain-lib/src/test/scala/com/socrata/soda/server/persistence/SodaPostgresContainerTest.scala
Before these would display as "invalid soql" because SF wouldn't know what to do with internal names it gets back from DC; now they display properly.
> Make listing rollups work with "legacy" new-analyzer rollups

- docker/soda-fountain.conf.j2
This avoids the issue of not having a RESOURCE_GROUPS_API_HOST present.
> EN-68825: Make j2 template safer for resource groups RESOURCE_GROUPS_API_HOST

- Jenkinsfile
This commit fixes a build error that happened on a hotfix -- the build tag was absent from the docker build command.
> EN-68827: fix hotfix build error

- Jenkinsfile
While working on migrating from marathon to ECS, we are keeping the tagged images up to date. This commit adds the mechanism for the ECS deployment in addition to the marathon deployment. Once the migration is done, we will remove the marathonDeploy and leave in place the ECS deployment.
> EN-76223: deploy to ECS as well as marathon
